(ns soap-stings.main
  (:gen-class)
  (:use [soap-stings.core]))

(defn -main [& args]
  (let [command (first args)
        params (rest args)]
    (when (= "list-virtual-servers" command)
      (println (list-virtual-servers)))
    (when (= "list-pool-names" command)
      (println (list-pool-names)))
    (when (= "list-draining-node" command)
      (println (list-draining-node (first params))))
    (when (= "add-node" command)
      (add-node (first params) (last params))
      (inspect (get-nodes (first params))))
    (when (= "get-nodes" command)
      (println (get-nodes (first params))))
    (when (= "remove-node" command)
      (remove-node (first params) (last params))
      (inspect (get-nodes (first params))))
    (when (= "drain-node" command)
      (drain-node (first params) (last params))
      (inspect (list-draining-node (first params))))
    (when (= "error-log" command)
      (println) (error-log))))
